### ISSUE TITLE
Update to AdminLTE v2.3.0?

### ISSUE THREAD

**Issue by cpg** [shine60vn/adminlte-rails#11]
Looks like you have kept up the development, however, the released gem is a little behind.

Would you consider updating to the theme's 2.3.0 release?

Also, I am not sure if this is related, but I get:

```
ActionController::RoutingError (No route matches [GET] "/assets/iCheck/minimal/minimal.png"):
```

because it looks like iCheck is not integrated completely with assets?

**Comment by cpg** [comment]
update: if i use
```
gem "adminlte-rails", :git => 'https://github.com/shine60vn/adminlte-rails'
```
i do not have an issue with broken checkboxes.

**Comment by shine60vn** [comment]
@cpg There are some new changes on `master` but I still have not released new version on Rubygems yet. In the roadmap, new features will be introduced, updating AdminLTE latest version is included as well. So the new release is coming soon. You can use `master` to solve your problem with iCheck as you mentioned above, sorry for this inconvenience!

**Comment by cpg** [comment]
Thank you. Maybe I can help.

I did notice that the header nav colors break while using `master`. See in this site I keep for [flex tennis leagues](http://www.racketlogger.com) where I started to use `master` without realizing that this would fail until it was deployed in production (it did not seem to happen in development -- probably due to caching in the browser or something).

Let me know how I can help. If nothing else, with testing.

**Comment by cpg** [comment]
Actually, using the top of the tree in `master` has a host of other issues.

I had to copy the icheck assets, however, iCheck broke all JS in my checkboxes. This is really not worth it.

Any progress on porting to the latest?

**Comment by cpg** [comment]
I decided to learn how to do this from scratch and I went ahead and created a gem (the css parts only) and it seems to be working more or less. I called it [lte-rails](https://github.com/racketlogger/lte-rails). I hope you don't mind it I did this. I found the internals of this gem a bit more complex than I could wrap my head around (I'm new to gems with assets). I did not do the JS parts yet.
