### ISSUE TITLE
checkbox background is missing, and its not showing

### ISSUE THREAD

**Issue by Vosa** [shine60vn/adminlte-rails#6]
Hi,
if I add checkbox mouse cursor recognize it, but its hidden and can't be checked. I found that in admin-lte.css on row 2862 is background image that is missing (icheck/miniminal/minimal.png).

Is there way to show checkbox, or I just have to set my own image in my custom css?

thx for help

**Comment by ugoa** [comment]
:+1:

**Comment by shine60vn** [comment]
Sorry for too late reply!

PR https://github.com/shine60vn/adminlte-rails/pull/4 fixed this issue already, we can close this now!
