### ISSUE TITLE
Not current version of Admin LTE 2. 

### ISSUE THREAD

**Issue by LankyT** [shine60vn/adminlte-rails#7]
The current version of AdminLTE2 is 2.1.2. 

Is there any chance this gem can be updated to the newest version?

Thank you!

**Comment by shine60vn** [comment]
Sorry, I no longer maintain this gem right now and the near future. If you need latest version of AdminLTE theme, please fork this repo and do it yourself. I could help you to know how this gem work, how to download assets... Please let me know if you need help!

**Comment by LankyT** [comment]
Thanks for the response. I'll give forking a shot.
