### ISSUE TITLE
couldn't find file 'admin-lte' with type 'application/javascript'

### ISSUE THREAD

**Issue by datomnurdin** [shine60vn/adminlte-rails#9]
I got this error message after I add this line in application.js
```
couldn't find file 'admin-lte' with type 'application/javascript'
```
application.js
```
//= require admin-lte
```

**Comment by shine60vn** [comment]
Which rails version you are using? Maybe the new rails version does not detect js files in `vendor` folder automatically. You can use this for workaround:
```
//= require ../../../vendor/assets/javascripts/admin-lte
```

Hope this help!

**Comment by datomnurdin** [comment]
Solved. I just restart the server.
